# Generated by Django 5.1.7 on 2025-06-29 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_hours', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('coordinates', models.JSONField()),
                ('type', models.CharField(choices=[('REST', 'Rest Stop'), ('FUEL', 'Fuel Stop'), ('BOTH', 'Rest and Fuel Stop')], max_length=4)),
                ('amenities', models.JSONField(default=dict)),
                ('planned_arrival', models.DateTimeField()),
                ('planned_departure', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_stops', to='route_planner.trip')),
            ],
            options={
                'ordering': ['planned_arrival'],
            },
        ),
    ]
