# Generated by Django 5.1.7 on 2025-06-29 00:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('route_planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_miles', models.FloatField(default=0)),
                ('starting_odometer', models.FloatField(default=0)),
                ('ending_odometer', models.FloatField(default=0)),
                ('carrier_name', models.CharField(blank=True, max_length=255)),
                ('carrier_address', models.CharField(blank=True, max_length=255)),
                ('driver_signature', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_sheets', to='route_planner.trip')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('trip', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DutyStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OFF', 'Off Duty'), ('SB', 'Sleeper Berth'), ('D', 'Driving'), ('ON', 'On Duty Not Driving')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('odometer', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_status_changes', to='eld_logs.logsheet')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
